from dataclasses import dataclass
from typing import Callable, List, Optional, Union
from homeassistant.components.sensor import SensorEntityDescription, SensorDeviceClass, SensorStateClass
from homeassistant.const import CURRENCY_DOLLAR, PERCENTAGE, EntityCategory


@dataclass(frozen=True)
class SharesightSensorDescription(SensorEntityDescription):
    sub_key: Optional[str] = None
    extension_key: Optional[str] = None
    native_value: Union[Callable[[Union[str, int, float]], Union[str, int, float]], None] = None
    device_group: Optional[str] = "portfolio"


CASH_SENSOR_DESCRIPTIONS: List[SharesightSensorDescription] = [
    SharesightSensorDescription(
        key='cash_accounts',
        sub_key="value",
        extension_key=None,
        name="CASH balance",
        icon="mdi:cash",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="cash"
    )
]

MARKET_SENSOR_DESCRIPTIONS: List[SharesightSensorDescription] = [
    SharesightSensorDescription(
        key='sub_totals',
        sub_key="value",
        extension_key=None,
        name="MARKET value",
        icon="mdi:finance",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="market"
    ),
    SharesightSensorDescription(
        key='sub_totals',
        sub_key="capital_gain",
        extension_key=None,
        name="MARKET capital gain",
        icon="mdi:cash-plus",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="market"
    ),
    SharesightSensorDescription(
        key='sub_totals',
        sub_key="capital_gain_percent",
        extension_key=None,
        name="MARKET capital gain percent",
        icon="mdi:sack-percent",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="market"
    ),
    SharesightSensorDescription(
        key='sub_totals',
        sub_key="total_gain",
        extension_key=None,
        name="MARKET total gain",
        icon="mdi:cash-plus",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="market"
    ),
    SharesightSensorDescription(
        key='sub_totals',
        sub_key="total_gain_percent",
        extension_key=None,
        name="MARKET total gain percent",
        icon="mdi:sack-percent",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="market"
    ),
    SharesightSensorDescription(
        key='sub_totals',
        sub_key="currency_gain",
        extension_key=None,
        name="MARKET currency gain",
        icon="mdi:cash-plus",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="market"
    ),
    SharesightSensorDescription(
        key='sub_totals',
        sub_key="currency_gain_percent",
        extension_key=None,
        name="MARKET currency gain percent",
        icon="mdi:sack-percent",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="market"
    ),
    SharesightSensorDescription(
        key='sub_totals',
        sub_key="payout_gain",
        extension_key=None,
        name="MARKET dividend gain",
        icon="mdi:hand-coin",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="market"
    ),
    SharesightSensorDescription(
        key='sub_totals',
        sub_key="payout_gain_percent",
        extension_key=None,
        name="MARKET dividend gain percent",
        icon="mdi:hand-coin",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="market"
    ),
    SharesightSensorDescription(
        key='sub_totals',
        sub_key="holding_count",
        extension_key=None,
        name="MARKET holding count",
        icon="mdi:format-list-numbered",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=0,
        device_group="market"
    ),
    SharesightSensorDescription(
        key='sub_totals',
        sub_key="cost_base",
        extension_key=None,
        name="MARKET cost basis",
        icon="mdi:cash-register",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="market"
    ),
]

SENSOR_DESCRIPTIONS: List[SharesightSensorDescription] = [
    SharesightSensorDescription(
        key="value",
        sub_key="report",
        extension_key=None,
        name="Portfolio value",
        icon="mdi:cash",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2
    ),
    SharesightSensorDescription(
        key="capital_gain",
        sub_key="report",
        extension_key=None,
        name="Capital gain",
        icon="mdi:cash-plus",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2
    ),
    SharesightSensorDescription(
        key="capital_gain_percent",
        sub_key="report",
        extension_key=None,
        name="Capital gain percent",
        icon="mdi:sack-percent",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2
    ),
    SharesightSensorDescription(
        key="total_gain",
        sub_key="report",
        extension_key=None,
        name="Total gain",
        icon="mdi:cash-plus",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2
    ),
    SharesightSensorDescription(
        key="total_gain_percent",
        sub_key="report",
        extension_key=None,
        name="Total gain percent",
        icon="mdi:sack-percent",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2
    ),
    SharesightSensorDescription(
        key="currency_gain",
        sub_key="report",
        extension_key=None,
        name="Currency gain",
        icon="mdi:cash-plus",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2
    ),
    SharesightSensorDescription(
        key="currency_gain_percent",
        sub_key="report",
        extension_key=None,
        name="Currency gain percent",
        icon="mdi:sack-percent",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2
    ),
    SharesightSensorDescription(
        key="payout_gain",
        sub_key="report",
        extension_key=None,
        name="Dividend gain",
        icon="mdi:cash-plus",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2
    ),
    SharesightSensorDescription(
        key="payout_gain_percent",
        sub_key="report",
        extension_key=None,
        name="Dividend gain percent",
        icon="mdi:sack-percent",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2

    ),
    SharesightSensorDescription(
        key="total_gain_percent",
        sub_key="one-day",
        extension_key="Extention",
        name="Daily Change Percent",
        icon="mdi:chart-line-variant",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="daily"
    ),
    SharesightSensorDescription(
        key="total_gain",
        sub_key="one-day",
        extension_key="Extention",
        name="Daily Change Amount",
        icon="mdi:chart-line-variant",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="daily"
    ),
    SharesightSensorDescription(
        key="total_gain",
        sub_key="one-week",
        extension_key="Extention",
        name="Weekly Change Amount",
        icon="mdi:chart-line-variant",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="weekly"
    ),
    SharesightSensorDescription(
        key="total_gain_percent",
        sub_key="one-week",
        extension_key="Extention",
        name="Weekly Change Percent",
        icon="mdi:chart-line-variant",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="weekly"
    ),
    SharesightSensorDescription(
        key="total_gain_percent",
        sub_key="financial-year",
        extension_key="Extention",
        name="Financial Year Change Percent",
        icon="mdi:chart-timeline-variant",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="financial_year"
    ),
    SharesightSensorDescription(
        key="total_gain",
        sub_key="financial-year",
        extension_key="Extention",
        name="Financial Year Change Amount",
        icon="mdi:chart-timeline-variant",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="financial_year"
    ),
    SharesightSensorDescription(
        key="portfolio_id",
        sub_key="report",
        extension_key=None,
        name="Portfolio ID",
        icon="mdi:identifier",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=2
    ),
    SharesightSensorDescription(
        key="user_id",
        sub_key="portfolios",
        extension_key=None,
        name="User ID",
        icon="mdi:identifier",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=2
    ),
    SharesightSensorDescription(
        key="currency_code",
        sub_key="portfolios",
        extension_key=None,
        name="Primary Currency",
        icon="mdi:cash",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC
    ),
    SharesightSensorDescription(
        key="name",
        sub_key="portfolios",
        extension_key=None,
        name="Portfolio Name",
        icon="mdi:briefcase",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC
    ),
    SharesightSensorDescription(
        key="financial_year_end",
        sub_key="portfolios",
        extension_key=None,
        name="Financial Year End",
        icon="mdi:calendar-end",
        native_unit_of_measurement=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC
    ),
    # All-time performance from report
    SharesightSensorDescription(
        key="cost_base",
        sub_key="report",
        extension_key=None,
        name="Cost Basis",
        icon="mdi:cash-register",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2
    ),
    SharesightSensorDescription(
        key="unrealised_gain",
        sub_key="report",
        extension_key=None,
        name="Unrealised Gain",
        icon="mdi:trending-up",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2
    ),
    SharesightSensorDescription(
        key="unrealised_gain_percent",
        sub_key="report",
        extension_key=None,
        name="Unrealised Gain Percent",
        icon="mdi:percent",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2
    ),
    SharesightSensorDescription(
        key="start_value",
        sub_key="report",
        extension_key=None,
        name="Portfolio Start Value",
        icon="mdi:flag-checkered",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2
    ),
    # Unconfirmed transactions across all holdings
    SharesightSensorDescription(
        key="unconfirmed_transactions",
        sub_key="holdings",
        extension_key=None,
        name="Unconfirmed Transactions",
        icon="mdi:alert-circle-outline",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=0,
        device_group="holdings"
    ),
    # Daily/Weekly start values from v2 performance
    SharesightSensorDescription(
        key="start_value",
        sub_key="one-day",
        extension_key="Extention",
        name="Daily Start Value",
        icon="mdi:flag-checkered",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="daily"
    ),
    SharesightSensorDescription(
        key="start_value",
        sub_key="one-week",
        extension_key="Extention",
        name="Weekly Start Value",
        icon="mdi:flag-checkered",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="weekly"
    ),
    SharesightSensorDescription(
        key="end_value",
        sub_key="one-day",
        extension_key="Extention",
        name="Daily End Value",
        icon="mdi:flag-variant",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="daily"
    ),
    SharesightSensorDescription(
        key="end_value",
        sub_key="one-week",
        extension_key="Extention",
        name="Weekly End Value",
        icon="mdi:flag-variant",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="weekly"
    ),
    SharesightSensorDescription(
        key="start_value",
        sub_key="financial-year",
        extension_key="Extention",
        name="Financial Year Start Value",
        icon="mdi:flag-checkered",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="financial_year"
    ),
    SharesightSensorDescription(
        key="end_value",
        sub_key="financial-year",
        extension_key="Extention",
        name="Financial Year End Value",
        icon="mdi:flag-variant",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="financial_year"
    ),
    # Daily breakdown sensors
    SharesightSensorDescription(
        key="capital_gain",
        sub_key="one-day",
        extension_key="Extention",
        name="Daily Capital Gain",
        icon="mdi:chart-line-variant",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="daily"
    ),
    SharesightSensorDescription(
        key="capital_gain_percent",
        sub_key="one-day",
        extension_key="Extention",
        name="Daily Capital Gain Percent",
        icon="mdi:chart-line-variant",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="daily"
    ),
    SharesightSensorDescription(
        key="currency_gain",
        sub_key="one-day",
        extension_key="Extention",
        name="Daily Currency Gain",
        icon="mdi:currency-usd",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="daily"
    ),
    SharesightSensorDescription(
        key="currency_gain_percent",
        sub_key="one-day",
        extension_key="Extention",
        name="Daily Currency Gain Percent",
        icon="mdi:currency-usd",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="daily"
    ),
    SharesightSensorDescription(
        key="payout_gain",
        sub_key="one-day",
        extension_key="Extention",
        name="Daily Dividend Gain",
        icon="mdi:hand-coin",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="daily"
    ),
    SharesightSensorDescription(
        key="payout_gain_percent",
        sub_key="one-day",
        extension_key="Extention",
        name="Daily Dividend Gain Percent",
        icon="mdi:hand-coin",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="daily"
    ),
    # Weekly breakdown sensors
    SharesightSensorDescription(
        key="capital_gain",
        sub_key="one-week",
        extension_key="Extention",
        name="Weekly Capital Gain",
        icon="mdi:chart-line-variant",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="weekly"
    ),
    SharesightSensorDescription(
        key="capital_gain_percent",
        sub_key="one-week",
        extension_key="Extention",
        name="Weekly Capital Gain Percent",
        icon="mdi:chart-line-variant",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="weekly"
    ),
    SharesightSensorDescription(
        key="currency_gain",
        sub_key="one-week",
        extension_key="Extention",
        name="Weekly Currency Gain",
        icon="mdi:currency-usd",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="weekly"
    ),
    SharesightSensorDescription(
        key="currency_gain_percent",
        sub_key="one-week",
        extension_key="Extention",
        name="Weekly Currency Gain Percent",
        icon="mdi:currency-usd",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="weekly"
    ),
    SharesightSensorDescription(
        key="payout_gain",
        sub_key="one-week",
        extension_key="Extention",
        name="Weekly Dividend Gain",
        icon="mdi:hand-coin",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="weekly"
    ),
    SharesightSensorDescription(
        key="payout_gain_percent",
        sub_key="one-week",
        extension_key="Extention",
        name="Weekly Dividend Gain Percent",
        icon="mdi:hand-coin",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="weekly"
    ),
    # Financial Year breakdown sensors
    SharesightSensorDescription(
        key="capital_gain",
        sub_key="financial-year",
        extension_key="Extention",
        name="Financial Year Capital Gain",
        icon="mdi:chart-timeline-variant",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="financial_year"
    ),
    SharesightSensorDescription(
        key="capital_gain_percent",
        sub_key="financial-year",
        extension_key="Extention",
        name="Financial Year Capital Gain Percent",
        icon="mdi:chart-timeline-variant",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="financial_year"
    ),
    SharesightSensorDescription(
        key="currency_gain",
        sub_key="financial-year",
        extension_key="Extention",
        name="Financial Year Currency Gain",
        icon="mdi:currency-usd",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="financial_year"
    ),
    SharesightSensorDescription(
        key="currency_gain_percent",
        sub_key="financial-year",
        extension_key="Extention",
        name="Financial Year Currency Gain Percent",
        icon="mdi:currency-usd",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="financial_year"
    ),
    SharesightSensorDescription(
        key="payout_gain",
        sub_key="financial-year",
        extension_key="Extention",
        name="Financial Year Dividend Gain",
        icon="mdi:hand-coin",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="financial_year"
    ),
    SharesightSensorDescription(
        key="payout_gain_percent",
        sub_key="financial-year",
        extension_key="Extention",
        name="Financial Year Dividend Gain Percent",
        icon="mdi:hand-coin",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="financial_year"
    ),
    # Holdings sensors
    SharesightSensorDescription(
        key="holding_count",
        sub_key="holdings",
        extension_key=None,
        name="Number of Holdings",
        icon="mdi:chart-box-multiple",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=0,
        device_group="holdings"
    ),
    SharesightSensorDescription(
        key="largest_holding_symbol",
        sub_key="holdings",
        extension_key=None,
        name="Largest Holding Symbol",
        icon="mdi:crown",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=None,
        device_group="holdings"
    ),
    SharesightSensorDescription(
        key="largest_holding_value",
        sub_key="holdings",
        extension_key=None,
        name="Largest Holding Value",
        icon="mdi:crown",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="holdings"
    ),
    SharesightSensorDescription(
        key="largest_holding_percent",
        sub_key="holdings",
        extension_key=None,
        name="Largest Holding Percent",
        icon="mdi:crown",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="holdings"
    ),
    SharesightSensorDescription(
        key="top_gain_symbol",
        sub_key="holdings",
        extension_key=None,
        name="Top Gain Symbol",
        icon="mdi:trending-up",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=None,
        device_group="holdings"
    ),
    SharesightSensorDescription(
        key="top_gain_amount",
        sub_key="holdings",
        extension_key=None,
        name="Top Gain Amount",
        icon="mdi:trending-up",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="holdings"
    ),
    SharesightSensorDescription(
        key="top_gain_percent",
        sub_key="holdings",
        extension_key=None,
        name="Top Gain Percent",
        icon="mdi:trending-up",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="holdings"
    ),
    SharesightSensorDescription(
        key="worst_gain_symbol",
        sub_key="holdings",
        extension_key=None,
        name="Worst Gain Symbol",
        icon="mdi:trending-down",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=None,
        device_group="holdings"
    ),
    SharesightSensorDescription(
        key="worst_gain_amount",
        sub_key="holdings",
        extension_key=None,
        name="Worst Gain Amount",
        icon="mdi:trending-down",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="holdings"
    ),
    SharesightSensorDescription(
        key="worst_gain_percent",
        sub_key="holdings",
        extension_key=None,
        name="Worst Gain Percent",
        icon="mdi:trending-down",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="holdings"
    ),
    # Income Report sensors
    SharesightSensorDescription(
        key="total_income",
        sub_key="income_report",
        extension_key=None,
        name="Total Dividend Income",
        icon="mdi:hand-coin",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="income"
    ),

    SharesightSensorDescription(
        key="dividend_count",
        sub_key="income_report",
        extension_key=None,
        name="Number of Dividends",
        icon="mdi:hand-coin",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=0,
        device_group="income"
    ),
    # Diversity sensors - Top 3 markets by percentage
    SharesightSensorDescription(
        key="market_1_name",
        sub_key="diversity",
        extension_key=None,
        name="Top Market 1 Name",
        icon="mdi:earth",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=None,
        device_group="diversity"
    ),
    SharesightSensorDescription(
        key="market_1_percent",
        sub_key="diversity",
        extension_key=None,
        name="Top Market 1 Percent",
        icon="mdi:earth",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="diversity"
    ),
    SharesightSensorDescription(
        key="market_1_value",
        sub_key="diversity",
        extension_key=None,
        name="Top Market 1 Value",
        icon="mdi:earth",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="diversity"
    ),
    SharesightSensorDescription(
        key="market_2_name",
        sub_key="diversity",
        extension_key=None,
        name="Top Market 2 Name",
        icon="mdi:earth",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=None,
        device_group="diversity"
    ),
    SharesightSensorDescription(
        key="market_2_percent",
        sub_key="diversity",
        extension_key=None,
        name="Top Market 2 Percent",
        icon="mdi:earth",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="diversity"
    ),
    SharesightSensorDescription(
        key="market_2_value",
        sub_key="diversity",
        extension_key=None,
        name="Top Market 2 Value",
        icon="mdi:earth",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="diversity"
    ),
    SharesightSensorDescription(
        key="market_3_name",
        sub_key="diversity",
        extension_key=None,
        name="Top Market 3 Name",
        icon="mdi:earth",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=EntityCategory.DIAGNOSTIC,
        suggested_display_precision=None,
        device_group="diversity"
    ),
    SharesightSensorDescription(
        key="market_3_percent",
        sub_key="diversity",
        extension_key=None,
        name="Top Market 3 Percent",
        icon="mdi:earth",
        native_unit_of_measurement=PERCENTAGE,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="diversity"
    ),
    SharesightSensorDescription(
        key="market_3_value",
        sub_key="diversity",
        extension_key=None,
        name="Top Market 3 Value",
        icon="mdi:earth",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=2,
        device_group="diversity"
    ),
    # Additional Holdings sensors - positive/negative counts
    SharesightSensorDescription(
        key="positive_holdings_count",
        sub_key="holdings",
        extension_key=None,
        name="Positive Holdings Count",
        icon="mdi:trending-up",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=0,
        device_group="holdings"
    ),
    SharesightSensorDescription(
        key="negative_holdings_count",
        sub_key="holdings",
        extension_key=None,
        name="Negative Holdings Count",
        icon="mdi:trending-down",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=0,
        device_group="holdings"
    ),
    # Income Report - last dividend date
    SharesightSensorDescription(
        key="last_dividend_date",
        sub_key="income_report",
        extension_key=None,
        name="Last Dividend Date",
        icon="mdi:calendar-check",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=None,
        suggested_display_precision=None,
        device_group="income"
    ),
    # Trades sensors
    SharesightSensorDescription(
        key="last_trade_date",
        sub_key="trades",
        extension_key=None,
        name="Last Trade Date",
        icon="mdi:calendar-clock",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=None,
        suggested_display_precision=None,
        device_group="trades"
    ),
    SharesightSensorDescription(
        key="last_trade_symbol",
        sub_key="trades",
        extension_key=None,
        name="Last Trade Symbol",
        icon="mdi:swap-horizontal",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=None,
        suggested_display_precision=None,
        device_group="trades"
    ),
    SharesightSensorDescription(
        key="last_trade_type",
        sub_key="trades",
        extension_key=None,
        name="Last Trade Type",
        icon="mdi:swap-horizontal-bold",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=None,
        entity_category=None,
        suggested_display_precision=None,
        device_group="trades"
    ),
    SharesightSensorDescription(
        key="last_trade_value",
        sub_key="trades",
        extension_key=None,
        name="Last Trade Value",
        icon="mdi:cash-fast",
        native_unit_of_measurement=CURRENCY_DOLLAR,
        device_class=SensorDeviceClass.MONETARY,
        state_class=None,
        entity_category=None,
        suggested_display_precision=2,
        device_group="trades"
    ),
    SharesightSensorDescription(
        key="trade_count_30d",
        sub_key="trades",
        extension_key=None,
        name="Trades Last 30 Days",
        icon="mdi:counter",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=0,
        device_group="trades"
    ),
    SharesightSensorDescription(
        key="total_trades",
        sub_key="trades",
        extension_key=None,
        name="Total Trades",
        icon="mdi:counter",
        native_unit_of_measurement=None,
        device_class=None,
        state_class=SensorStateClass.TOTAL,
        entity_category=None,
        suggested_display_precision=0,
        device_group="trades"
    ),
]
